### PR TITLE
fix: Redact passwords from SCM URLs.

### LINKED ISSUE #119: Metrics export leaks Git access token on GitLab
When running on a GitLab runner, the detected SCM URL reported on metrics leaks the GitLab access token used to retrieve the repository.  This URL should be sanitized.

Image

### PR DESCRIPTION
**Pull request by asgeirn**
Fixes #119

### CODE REVIEW

**Review by mdelapenya — COMMENTED** [review]
Thanks for the contribution, it looks good to me.

Could you add a unit test covering this case for the contribute attributes method? 🙏

**Comment by asgeirn** [comment]
Added a unit test now; this did require some trickery as GitHub does not accept a fake authorization header even if the repository is public.

File: git_proxy.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
+package main
+
+import (
+	"net/http"
+	"net/http/httptest"
+	"net/http/httputil"
+	"net/url"
+)
+
+type TestProxy struct {
```
Comment (mdelapenya) [inline git_proxy.go:10]: suggestion: even tough this lives in the main package, I'd try to avoid exporting this test helper. Even moving it to a test file could be of interest. Thoughts?

Comment (asgeirn) [reply git_proxy.go]: Moved it to a separate package now, is this better?

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!
